mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=springstudent
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=root
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
  depends_on:
    - mysql-server